name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12:30am and 12:30pm UTC
    - cron: '30 0,12 * * *'

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          #GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: 'true'
          SHOW_LINES_OF_CODE: 'True'
          SHOW_LOC_CHART: 'False'
          LOCALE: 'en'
          SHOW_EDITORS: 'true'
